name: Mobile
on: workflow_dispatch
jobs:
  Android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Android NDK
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r21e
      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib --quiet install hmm
          haxelib run hmm install --quiet
          haxelib install flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install hscript
          haxelib install hscript
          haxelib install akifox-asynchttp
          haxelib install flixel-addons
          haxelib install newgrounds
          haxelib install linc_luajit
          haxelib install hxp
          haxelib git faxe https://github.com/uhrobots/faxe
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git hscript-yoshiengine https://github.com/YoshiCrafter29/hscript-improved
          haxelib git discord_rpc_yce https://github.com/YoshiCrafter29/linc_discord-rpc
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
          haxelib git flixel-textureatlas-yoshiengine https://github.com/YoshiCrafter29/Flixel-TextureAtlas-YoshiCrafterEngine
          haxelib git hscript-yoshiengine https://github.com/YoshiCrafter29/hscript-improved
          haxelib git flixel-yc29 https://github.com/YoshiCrafter29/flixel
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec
          haxelib git spinehaxe https://github.com/bendmorris/spinehaxe
      - name: Configure Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Compile
        run: haxelib run lime build android -final
        env:
          cert_pass: nullfunni
          cert_alias_pass: nullfunni
      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
          if-no-files-found: error
  iOS:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib --quiet install hmm
          haxelib run hmm install --quiet
      - name: Compile
        run: haxelib run lime build ios -final
      - name: Make Ipa
        run: |
          cd export/release/ios/build/Release-iphoneos
          mkdir Payload
          mv *.app Payload
          zip -r CodenameEngine.ipa Payload
      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: iOSBuild
          path: export/release/ios/build/Release-iphoneos/*.ipa
          if-no-files-found: error
